### ISSUE TITLE
请问机器人回消息的时候每次都要回好几条，如何能合并到一条

### ISSUE THREAD

**Issue by lihkhy** [bincooo/webgpt-bot#4]

**Comment by bincooo** [comment]
因为我为了加快响应，做了断句处理。
如果你不想这样，就需要自行修改代码，具体可以看看：
https://github.com/bincooo/webgpt-bot/blob/main/src/utils.ts :: 65行 onMessage

**Comment by lihkhy** [comment]
谢谢
